### ISSUE TITLE
Reg generating docs for components

### ISSUE THREAD

**Issue by SanyasiraoM** [react-native-material-design/react-native-material-design#151]
Hi, How did you guys generated the documentation as like in http://react-native-material-design.github.io

Did you guys used any automation tools?

@bozzmob  @Ehesp  @Salakar Can you look into this?

Thank you :)

**Comment by Ehesp** [comment]
Nothing is used to generate them at the moment. All manual.

Would probably be best to move away from from site and keep them within the
repo

On 3 Apr 2017 7:01 am, "SanyasiraoM" <notifications@github.com> wrote:

Hi, How did you guys generated the documentation as like in
http://react-native-material-design.github.io

Did you guys used any automation tools?

@bozzmob <https://github.com/bozzmob> @Ehesp <https://github.com/Ehesp>
@Salakar <https://github.com/Salakar> Can you look into this?

Thank you :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/react-native-material-design/react-native-material-design/issues/151>,
or mute the thread

**Comment by SanyasiraoM** [comment]
Thanks for reply :)
