### ISSUE TITLE
Cannot find icons

### ISSUE THREAD

**Issue by PatrickEriksen** [react-native-material-design/react-native-material-design#30]
I receive the following error:
> Requiring unknown module "react-native-vector-icons/MaterialIcons". If you are sure the module is there, try restarting the packager.

I'm using:
>    "react-native-material-design": "^0.3.2",
>    "react-native-vector-icons": "^1.2.0"

I have copied over the fonts as described to:
android/app/src/main/java/assets/fonts

**Comment by Strainy** [comment]
Downgrade to react-native 0.18.0 as per the demo app. There seem to be some big changes to how the Java/Android stuff is structured in the later versions.

I had a bit of trouble downgrading. Just the changing the react-native version in your projects `package.json` file and re-running `npm install` didn't seem to be enough since you also have to rebuild/rollback the generated android code. To do this just run `react-native upgrade` in your project folder and follow the prompts to overwrite all the generated android files.

**Comment by Ehesp** [comment]
I've not had chance to really test on the latest React release due to work, but will pick it up when I can as I'm going to be building an app again soon with it.

**Comment by adnbsr** [comment]
This issue is not related to RN version, but since fonts files is copied, packager should be restarted and android project should be rebuilt.

**Comment by PatrickEriksen** [comment]
I had to downgrade to .18 and then upgrade. this is so weird.
